### ISSUE TITLE
Agregar fotos faltantes

### ISSUE THREAD

**Issue by martinszy** [representacion/pigmentocracia#4]
ID | NOMBRE_DIPUTADO_ELECTO_2024 | PARTIDO_2024 | NOMBRE_ENTIDAD | NOMBRE_DISTRITO_FEDERAL | ENTIDAD | DISTRITO_FEDERAL
-- | -- | -- | -- | -- | -- | --
6349 | Elda Esther Del Carmen Castillo Quintana | MORENA | CAMPECHE | CAMPECHE | 4 | 1
4620 | Francisco Javier Sánchez Cervantes | PT | CIUDAD DE MEXICO | IZTACALCO | 9 | 13
4711 | Alma Rosa De La Vega Vargas | MORENA | GUANAJUATO | SAN MIGUEL DE ALLENDE | 11 | 2
4747 | Tatiana Tonantzin P. Angeles Moreno | MORENA | HIDALGO | ACTOPAN | 13 | 3
4751 | Mirna María De La Luz Rubio Sánchez | MORENA | HIDALGO | TEPEAPULCO | 13 | 7
4814 | Sandra Beatriz González Pérez | MORENA | JALISCO | TLAJOMULCO DE ZUÐIGA | 14 | 12
4935 | Anay Beltran Reyes | MORENA | MEXICO | TULTITLAN | 15 | 8
4857 | Alma Monserrat Córdoba Navarrete | MORENA | MEXICO | ECATEPEC DE MORELOS | 15 | 13
4919 | Gabriela Valdepeñas González | PT | MEXICO | TLALNEPANTLA DE BAZ | 15 | 19
4921 | Iván Millán Contreras | MORENA | MEXICO | AMECAMECA | 15 | 21
6791 | Wblester Santiago Pineda | MORENA | MEXICO | METEPEC | 15 | 27
4960 | Delhi Miroslava Shember Domínguez | PT | MICHOACAN DE OCAMPO | ZAMORA | 16 | 5
6751 | Cindy Winkler Trujillo | PVEM | MORELOS | CUAUTLA | 17 | 3
5049 | José Alejandro López Sánchez | MORENA | OAXACA | HEROICA CIUDAD DE TLAXIACO | 20 | 6
1695 | María del Carmen Bautista Pelaéz | MORENA | OAXACA | SAN PEDRO MIXTEPEC | 20 | 9
5029 | Carmelo Cruz Mendoza | MORENA | OAXACA | MIAHUATLAN DE PORFIRIO DIAZ | 20 | 10
5092 | Rafaela Vianey García Romero | MORENA | PUEBLA | SAN MARTIN TEXMELUCAN | 21 | 5
5093 | Carlos Ignacio Mier Bañuelos | PVEM | PUEBLA | CHALCHICOMULA DE SESMA | 21 | 8
5142 | José Luis Fernández Martínez | PT | SAN LUIS POTOSI | SOLEDAD DE GRACIANO SANCHEZ | 24 | 2
5143 | Francisco Adrián Castillo Morales | MORENA | SAN LUIS POTOSI | CIUDAD VALLES | 24 | 4
5255 | Jorge Alberto Mier Acolt | MORENA | VERACRUZ DE IGNACIO DE LA LLAVE | EMILIANO ZAPATA | 30 | 8
5277 | Zenyazen Roberto Escobar García | PVEM | VERACRUZ DE IGNACIO DE LA LLAVE | CORDOBA | 30 | 16
5278 | Benito Aguas Atlahua | MORENA | VERACRUZ DE IGNACIO DE LA LLAVE | ZONGOLICA | 30 | 18

**Comment by Arpitoxd** [comment]
Listo
